### PR TITLE
Add osgi bundle capability

### PR DESCRIPTION
**Pull request by Naios**
* which enables the possibility to deploy DockFX
  in an osgi environment (equinox/felix...).
* convert tabs 2 spaces in edited regions.

screenshot_1

Note: System classloader JavaFX workarround is still required to deploy JavaFX bundles into osgi:
- e(fx)clipse or similar
- or adding javafx classpath to `org.osgi.framework.system.packages.extra`.

### CODE REVIEW

**Comment by Naios** [comment]
I don't know what causes the warning, but without the entry:

```xml
<executions>
    <execution>
        <id>bundle-manifest</id>
        <phase>process-classes</phase>
        <goals>
            <goal>manifest</goal>
        </goals>
    </execution>
</executions>
```

the maven-bundle-plugin doesn't get executed.

**Comment by RobertBColton** [comment]
@Naios I think I understand what it is, I believe it is M2E not knowing how to execute the plugin.
http://stackoverflow.com/questions/9142533/plugin-execution-not-covered-by-lifecycle-configuration-jbossas-7-ear-archetype
Can you take a look and see if you can make the changes to make this go away? I am not exactly sure how to do this but I don't believe I specifically will need the dependency but other Eclipse users may.

**Comment by Naios** [comment]
From [Stackoverflow](http://stackoverflow.com/questions/9142533/plugin-execution-not-covered-by-lifecycle-configuration-jbossas-7-ear-archetype) and i think he is right about it:
> I don't understand the concept. M2E should be transparent to the user. Do what that the command line Maven does, but from within eclipse. There should not be in the pom config data to tell M2E what to do. If it does, then it's a bad design. BTW, these errors are sometimes gone in newer versions of Eclipse and M2E. –  rapt Apr 11 '13 at 18:19 

I think the best solution would be to ignore the error in eclipse since it won't pollute the pom:

screenshot_2

**Comment by RobertBColton** [comment]
@Naios Thank you it does seem most of the replies indicate this is more of an M2E meta-data issue than anything to do with Maven. I'm going to go ahead and pull, thank you for supporting my project, your contributions are appreciated!

**Pull request merged**
